# Generated by Django 4.1.7 on 2023-04-06 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "add_id",
                    models.AutoField(default=0, primary_key=True, serialize=False),
                ),
                ("address", models.CharField(max_length=255)),
                ("zipcode", models.CharField(max_length=255)),
            ],
            options={"db_table": "Address",},
        ),
        migrations.CreateModel(
            name="Authenticate",
            fields=[
                ("p_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=15)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("Customer", "Customer"),
                            ("Manager", "Manager"),
                            ("DeliveryPerson", "DeliveryPerson"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
            options={"db_table": "Authenticate",},
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("Category_id", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=255)),
            ],
            options={"db_table": "Category",},
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("f_name", models.CharField(max_length=255)),
                ("l_name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                (
                    "p_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_delivery_app.authenticate",
                    ),
                ),
            ],
            options={"db_table": "Customer",},
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                ("delivery_id", models.AutoField(primary_key=True, serialize=False)),
                ("timeDispatch", models.DateTimeField(null=True)),
                ("timeArrival", models.DateTimeField(null=True)),
            ],
            options={"db_table": "Delivery",},
        ),
        migrations.CreateModel(
            name="deliveryPersonnel",
            fields=[
                ("personnel_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("Delivering", "Delivering"),
                            ("Available", "Available"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "p_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_delivery_app.authenticate",
                    ),
                ),
            ],
            options={"db_table": "deliveryPersonnel",},
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                ("manager_id", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                (
                    "p_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_delivery_app.authenticate",
                    ),
                ),
            ],
            options={"db_table": "Manager",},
        ),
        migrations.CreateModel(
            name="payInfo",
            fields=[
                ("infoId", models.AutoField(primary_key=True, serialize=False)),
                ("payMode", models.CharField(max_length=100)),
                ("payDescr", models.CharField(max_length=100)),
                (
                    "custId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_delivery_app.customer",
                    ),
                ),
            ],
            options={"db_table": "payInfo",},
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("item_name", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
                ("description", models.CharField(max_length=255)),
            ],
            options={"db_table": "Product",},
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                ("restaurant_id", models.AutoField(primary_key=True, serialize=False)),
                ("restaurant_name", models.CharField(max_length=255)),
                (
                    "addr_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_delivery_app.address",
                    ),
                ),
                (
                    "man_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_delivery_app.manager",
                    ),
                ),
            ],
            options={"db_table": "Restaurant",},
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                ("status_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status_val",
                    models.CharField(
                        choices=[
                            ("Processing", "Processing"),
                            ("Out For Delivery", "Out For Delivery"),
                            ("Delivered", "Delivered"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
            options={"db_table": "Status",},
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("review_id", models.AutoField(primary_key=True, serialize=False)),
                ("stars", models.IntegerField()),
                ("del_rev", models.CharField(max_length=255)),
                ("food_rev", models.CharField(max_length=255)),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_delivery_app.customer",
                    ),
                ),
                (
                    "delivery_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_delivery_app.delivery",
                    ),
                ),
            ],
            options={"db_table": "Review",},
        ),
        migrations.CreateModel(
            name="restPhNos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ph_no", models.CharField(max_length=255)),
                (
                    "restaurant_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_delivery_app.restaurant",
                    ),
                ),
            ],
            options={"db_table": "restPhNos",},
        ),
        migrations.CreateModel(
            name="Product_categ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cat_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_delivery_app.category",
                    ),
                ),
                (
                    "prod_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_delivery_app.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="res_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="food_delivery_app.restaurant",
            ),
        ),
        migrations.CreateModel(
            name="personnelAddr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_delivery_app.address",
                    ),
                ),
                (
                    "personnel_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_delivery_app.deliverypersonnel",
                    ),
                ),
            ],
            options={"db_table": "personnelAddr",},
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("payId", models.AutoField(primary_key=True, serialize=False)),
                ("payDate", models.DateTimeField()),
                (
                    "infoId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_delivery_app.payinfo",
                    ),
                ),
            ],
            options={"db_table": "Payment",},
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                ("total_price", models.IntegerField()),
                ("ordered_on", models.DateTimeField(auto_now=True)),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_delivery_app.customer",
                    ),
                ),
                (
                    "restaurant_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_delivery_app.restaurant",
                    ),
                ),
            ],
            options={"db_table": "Orders",},
        ),
        migrations.CreateModel(
            name="orderProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "item_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_delivery_app.product",
                    ),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_delivery_app.orders",
                    ),
                ),
            ],
            options={"db_table": "orderProducts",},
        ),
        migrations.CreateModel(
            name="ManNos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ph_no", models.CharField(max_length=255)),
                (
                    "man_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_delivery_app.manager",
                    ),
                ),
            ],
            options={"db_table": "ManNos",},
        ),
        migrations.AddField(
            model_name="delivery",
            name="orderId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="food_delivery_app.orders",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="personnelId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="food_delivery_app.deliverypersonnel",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="statusId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="food_delivery_app.status",
            ),
        ),
        migrations.CreateModel(
            name="CustNos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ph_no", models.CharField(max_length=255)),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_delivery_app.customer",
                    ),
                ),
            ],
            options={"db_table": "CustNos",},
        ),
        migrations.CreateModel(
            name="CustAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_delivery_app.address",
                    ),
                ),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_delivery_app.customer",
                    ),
                ),
            ],
            options={"db_table": "CustAddress",},
        ),
    ]
