# Generated by Django 4.1.7 on 2023-04-07 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("food_delivery_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="deliverypersonnel", name="availability",),
        migrations.CreateModel(
            name="availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "available",
                    models.CharField(
                        choices=[
                            ("Delivering", "Delivering"),
                            ("Available", "Available"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_delivery_app.deliverypersonnel",
                    ),
                ),
            ],
            options={"db_table": "Availability",},
        ),
    ]
