# Generated by Django 4.1.7 on 2023-04-07 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "food_delivery_app",
            "0002_remove_deliverypersonnel_availability_availability",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="availability", old_name="available", new_name="availability",
        ),
    ]
