# Generated by Django 4.1.7 on 2023-04-07 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("food_delivery_app", "0003_rename_available_availability_availability"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverypersonnel",
            name="addr_id",
            field=models.ForeignKey(
                
                on_delete=django.db.models.deletion.CASCADE,
                to="food_delivery_app.address",
            ),
        ),
    ]
