# Generated by Django 4.1.7 on 2023-04-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_delivery_app", "0005_delete_personneladdr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="status_val",
            field=models.CharField(
                choices=[
                    ("Processing", "Processing"),
                    ("Out For Delivery", "Out For Delivery"),
                    ("Delivered", "Delivered"),
                ],
                default="Processing",
                max_length=255,
            ),
        ),
    ]
