# Generated by Django 4.1.7 on 2023-04-11 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("food_delivery_app", "0008_alter_payinfo_paymode"),
    ]

    operations = [
        migrations.CreateModel(
            name="restaurantPersonnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_delivery_app.deliverypersonnel",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_delivery_app.restaurant",
                    ),
                ),
            ],
            options={"db_table": "RestaurantPersonnel",},
        ),
    ]
