# Generated by Django 4.1.7 on 2023-04-11 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("food_delivery_app", "0010_rename_item_id_orderproducts_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="addr_id",
            field=models.ForeignKey(
                
                on_delete=django.db.models.deletion.CASCADE,
                to="food_delivery_app.address",
            ),
        ),
    ]
