# Generated by Django 4.1.7 on 2023-04-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food_delivery_app", "0012_alter_orders_addr_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="product_categ", name="cat_id",),
        migrations.RemoveField(model_name="product_categ", name="prod_id",),
        migrations.DeleteModel(name="Category",),
        migrations.DeleteModel(name="Product_categ",),
    ]
