# Generated by Django 4.1.7 on 2023-04-11 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("food_delivery_app", "0013_remove_product_categ_cat_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="payment", name="infoId",),
        migrations.AddField(
            model_name="payment",
            name="cust_id",
            field=models.ForeignKey(
                
                on_delete=django.db.models.deletion.CASCADE,
                to="food_delivery_app.customer",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="order_id",
            field=models.ForeignKey(
            
                on_delete=django.db.models.deletion.CASCADE,
                to="food_delivery_app.orders",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payMode",
            field=models.CharField(
                choices=[("Cash", "Cash"), ("Card", "Card")],
                default="Cash",
                max_length=100,
            ),
        ),
        migrations.DeleteModel(name="payInfo",),
    ]
