# Generated by Django 4.1.7 on 2023-04-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "food_delivery_app",
            "0015_alter_payment_cust_id_alter_payment_order_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverypersonnel",
            name="availability",
            field=models.CharField(
                choices=[("Delivering", "Delivering"), ("Available", "Available")],
                default="Available",
                max_length=255,
            ),
        ),
    ]
