# Generated by Django 4.1.7 on 2023-04-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_delivery_app", "0016_deliverypersonnel_availability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverypersonnel",
            name="availability",
            field=models.CharField(
                choices=[("Delivering", "Delivering"), ("Available", "Available")],
                default=("Available", "Available"),
                max_length=255,
            ),
        ),
    ]
